platform :ios, '10.0'
use_frameworks!

# common pods
# Para expecificar versión
#   pod 'FillableLoaders', '~>1.3.0'

def common_pods
   common_pods
end

target 'MadridEvent' do
   common_pods
end

target 'MadridEventTests' do
   common_pods
end
